name: Deploy User Delete Microservice

on:
  push:
    branches:
      - test

jobs:
  deploy-user-delete:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build and push Docker image for user-delete-microservice
      - name: Build and push Docker image for user-delete-microservice
        run: |
          cd user-delete-microservice  # Cambiar al directorio donde está el Dockerfile
          docker build -t alexismendozaa/user-delete-microservice .
          docker push alexismendozaa/user-delete-microservice:latest

      # 5. Set up SSH key for deployment
      - name: Set up SSH key for deployment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST_DELETE }} >> ~/.ssh/known_hosts

      # 6. SSH to EC2 and deploy
      - name: SSH to EC2 and deploy
        run: |
          echo "Iniciando despliegue en EC2..."
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST_DELETE }} << 'EOF'
            # Detén y elimina cualquier contenedor anterior
            docker stop user-delete-microservice || true
            docker rm user-delete-microservice || true

            # Pull del nuevo contenedor desde DockerHub
            docker pull alexismendozaa/user-delete-microservice:latest

            # Ejecuta el contenedor (en el puerto 4000)
            docker run -d -p 4000:4000 --name user-delete-microservice \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              alexismendozaa/user-delete-microservice:latest

            echo "Despliegue completo. El contenedor está en ejecución."
          EOF
